### ISSUE TITLE
Integrated circuits add delays when using the 'electron' emulation algorithm, despite text stating they do not make things slower

### ISSUE THREAD

**Issue by Tynach** [lvandeve/logicemu#7] opened 2020-09-22 01:06 UTC
This is particularly evident in [16-bit ripple vs lookahead speed comparison][lasc], which is also - ironically - where the text, "Using a chip has no effect on speed," occurs (despite the fact that this circuit defaults to using electron mode).

# To reproduce:
While that circuit *does* demonstrate the problem very noticeably, you have to do a bit of work to set up the inputs to not affect more components along the way.

Not wanting to write out a specific set of instructions for how to set up the inputs and whatnot in that fairly large circuit, here's a simpler way to demonstrate the issue:

1. Open the [IC help page][ic].
2. Set the 'Emulation Algorithm' to 'electron'.
3. Click one of the inputs in the IC definition.
4. Look at the number of ticks, and maybe copy that value to a text editor so you can remember it.
5. Clear the number of ticks by clicking it.
6. On the circuit using the IC instance, click the input corresponding to whatever input in the IC definition you had clicked before (should still be clicked).
7. Compare the resulting number of ticks to what you noticed before when clicking one of the definition's inputs.

[The circuit used for those steps][ic] implements a single full adder, and has a single instance of that full adder. When using the 'electron' emulation algorithm and clicking on the inputs in the definition itself, the `A` and `B` inputs (the first two) result in a 4 tick delay. The input corresponding to the adder's `Cin` (carry in) pin results in a 3 tick delay.

## Expected Results:
I would expect that clicking on the inputs to the lone instance of the IC, with simple LED outputs corresponding to each of the outputs from the IC itself, would result in identical delays.

## Actual Results:
However, that is not the case... Instead there is an additional 3-tick delay added on top.

For the `A` and `B` inputs, the tick turns from only 4 ticks, to 7 ticks; and clicking the `Cin` input leads to the delay growing from 3 ticks, to 6 ticks.

# Conclusion
I've tested it in both Firefox and Chrome, and it remains the same. If I were to take a naive stab in the dark at *why* this happens, I'd guess that since LEDs and wires have a 1 tick delay to changing (or at least, they *seem* to), that delay is also present in the ICs; that is, the input wires don't count as the same wires within an IC (instead behaving as.. I don't know, inputs to those wires? The switches themselves?).

I feel like that would add only 2 ticks of additional delay, while what I'm finding is a relatively consistent 3 ticks of extra delay per operation. Regardless, this is *not* what the help text states, and I couldn't find the current behavior documented anywhere.

[lasc]: https://lodev.org/logicemu/#id=cla_adder_speed
[ic]: https://lodev.org/logicemu/#id=component163

**Comment by lvandeve** [comment] 2020-09-22 16:34
Thanks for reporting this, I could reproduce it using the 'pause' button, enabling input switches, and pressing the tick manually, and indeed the IC currently adds 3 ticks of delay.

That's more than intended so that's a bug. I'll try to reduce it as much as possible. If I don't get it all the way from 3 to 0, but 1 or 2 remain (I'm optimistic at least one can be removed!), I'll fix the documentation to match that.

**Comment by Tynach** [comment] 2020-09-22 19:08
@lvandeve would it work to simply remove the delay associated with LEDs, and instead have LEDs act as 'current status' probes for wires? And maybe also have switches' states shared with their output wires' states (like how gates work), instead of there being a 1-tick delay before a switch changes a wire's state?

**Comment by lvandeve** [comment] 2020-09-22 22:27
Commit 34a6b6355348df0940804640897c2e9e0841d50 removed 1 of 3 ticks of delay, 1 more may be done later. Also changed the note about the delay

About LEDs: LEDs are treated as components so will always have the delay in electron mode. Maybe a glowing wire could be introduced as a new type of wire that can act as a type of lamp, that wouldn't need an input and thus not be a separate component. Would that be useful?

About switches: a switch should already work like any other component and gate, its output wire should toggle immediately, and I also observe this in electron mode (color of wire and switch change at same time). Which delay in switches do you observe?

**Comment by Tynach** [comment] 2020-09-23 01:15
The 1 tick delay when paused is what I was observing. The only two delays I could think of would be:

1. If there were a delay between the input wire turning on, and the switch inside the instance turning on, and
2. If there were a delay between the output LED turning on and the instance output wire turning on.

My main theory regarding the third delay was that the 1 tick delay observed when paused and toggling a switch was perhaps causing it, but I don't believe that to be the case after studying the behavior of other components when paused (just today I learned about Ctrl+Clicking to toggle a component between itself and its inverted output variant).

Would it not be possible to remove the switches and LEDs inside the instances, instead just treating the input wires as being the same wires as the wires leading from what used to be the switches? Basically treating - as far as the simulation is concerned - each instance of an IC as new copies of each internal component, removing switches and LEDs, and instead replacing those switches and LEDs with the input and output wires?

For example, on a 2-bit full adder composed of two ICs each implementing a 1-bit full adder, the OR gate of the least significant full adder would be wired directly into the AND and XOR gates of the second full adder's second half adder.

That's the sort of behavior I would expect from tools that behave as subcircuits/integrated circuits/custom components.

**Comment by Tynach** [comment] 2020-09-23 02:23
It's worth noting that your change in the description is still somewhat inaccurate, because there *are* cases where this bug causes the ripple carry adder to be faster, even with only 2 ticks of delay.

The expression `31 + 1` always evaluates faster in the ripple adder (13 ticks) than in the lookahead adder (14 ticks), and in general it seems that numbers that differ only in the 5 least significant bits will add faster on the ripple-carry adder.

**Comment by lvandeve** [comment] 2020-09-24 23:02
One more tick removed with commit ad8c411117481b24820e94df7ea52fa95dd5ecb6, the two removed ones are by bypassing that input/output switch/LED in the IC. One more tick to remove. Also updated the comment of the speed comparison circuit.

**Comment by lvandeve** [comment] 2020-09-24 23:37
Final delay removed with commit 78b16802f4901a1d08ad4f108db2be181175890e, this should make ICs equivalent to having the underlying circuit present in its place.

Thanks for reporting this. This should be fully fixed now, feel free to re-open if not.

**Closed by lvandeve** 2020-09-24 23:37 UTC

**Comment by Tynach** [comment] 2020-09-27 19:52
Awesome! Works great so far!
